Develop
ivaan1992/Portfolio1 pull request #1
Opened 2021-08-13 19:25 UTC by ivaan1992

This is the first part of the portfolio from this week.

2021-08-13 20:54 UTC, dasileker reviewed
### **Hi @ivaan1992** 

### **Project Invalid❌❌❌**

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no linters check you will say they are added, but see the screenshot 👇 there is no Eslint, or StyleLint.
![li](https://user-images.githubusercontent.com/61562626/129417175-51e5d0b8-f07c-4472-bdb4-7e63d7a9c747.jpeg)

- Also the PR is poor in description, you need to explain more about the project see the screenshot 👇 add more specific description of the project and the tools.
![rp](https://user-images.githubusercontent.com/61562626/129417419-189153b7-6228-4eab-964b-9249ad72bc56.jpeg)



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-08-14 03:38 UTC, Murodjon000 requested changes
**Hi Ivan Linares Gaona 👋,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] It would be better if you give to your page full with because now your page is not fully fitting to the window. Try to give fully with to your styling.
-  This is the design you did.
 ![](https://res.cloudinary.com/dflkwvvnz/image/upload/v1628911041/scrnli_8_14_2021_8-16-38_AM_uf8rna.png)
- As you see, first remove the mobile icons in the header section and give to your container full with in order to make your design the same as the Fimga design 😃.

### _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 03:38 UTC, Murodjon000 commented on index.html
> +    </div>
- [ ] Kindly use the `header` tag instead of the `div` tag in order to make your code Semantic. Because this is the header section and you are using the `div` tag as a wrapper, you can do it if you wrap this `div` tag with the `header` then your code will be perfect 🙌. To get more information about Semantic HTML, see this [link](https://www.freecodecamp.org/news/semantic-html5-elements/).

2021-08-14 03:38 UTC, Murodjon000 commented on index.html
> +
- [ ] It would be better if you use the `nav` tag inside your `header` section because of Semantic HTML. Please use the `nav` tag for your navigations. See this [link ](https://www.freecodecamp.org/news/semantic-html5-elements/)to get information about Semantic HTML 🙏.

2021-08-14 03:38 UTC, Murodjon000 commented on index.html
> +                  <li class = "padding"><img src = "images/Battery.png" alt = ""></li>
- [ ] I think you don't need phone decorations, instead of this only put your navigations that you need. These icons will make your UI not good. Use your navigations with `a` tag also 😃.

2021-08-14 03:38 UTC, Murodjon000 commented on index.html
> +</div>
- [ ] Please wrap your main section with a `main` tag in order to make your code Semantic.

2021-08-14 03:38 UTC, Murodjon000 commented on style.css
> +  display: flex;
- [ ] Please avoid using one style multiple times and stick to the DRY principle. Because repeating your code in many places makes your code repetitive and not clean. Kindly change all the repeated stylings in your code in order to make your code clean and perfect 👏.
- [ ]  Little hint for you:
-  `.flex {
display:flex
}`

2021-08-14 16:47 UTC, mke2111 requested changes
### Hey @ivaan1992, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 16:49 UTC, mke2111 commented on index.html
> +    </header>
- [ ] As requested earlier on, implement this feature
>  It would be better if you use the nav tag inside your header section because of Semantic HTML. Please use the nav tag for your navigations.

2021-08-14 17:17 UTC, safafa approved these changes
## STATUS: APPROVED 🟢 👏
Hello, @ivaan1992  great job working on the requested changes 👍 💯
I left you an optional change. Check the inline comment for it.
Congratulations !! Now you can merge this branch 💪 😄
HAPPY CODING!! AND GOOD LUCK WITH THE NEXT ONES 🤞 🍀

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 17:17 UTC, safafa commented on index.html
> +            <h4 class = "name">Ivan Gaona</h4>
- [ ] [OPTIONAL] The logo should be a clickable link. Kindly fix the issue.

2021-08-15 01:20 UTC, merged